"""Creative Director router — multimodal interleaved content generation.

POST /api/v1/creative-director/generate
POST /api/v1/creative-director/generate-stream  (SSE)

  Runs the Gemini interleaved Creative Director to produce rich, mixed-media
  packages (text + generated images in a single fluid output stream) from a
  creative brief and chosen mode.

Modes
-----
  storybook        Alternating story paragraphs + inline illustrations
  marketing        Headline + hero image + body copy + CTA visual + hashtags
  educational      Narration sections woven with concept/diagram images
  social_content   Caption + post image + secondary carousel + hashtag cloud

The underlying Gemini call uses response_modalities=["TEXT", "IMAGE"] which
instructs the model to natively interleave text and generated images — all in
one API round-trip. No post-processing assembly required.
"""

from __future__ import annotations

import json
import logging
from uuid import uuid4

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from models.schemas import (
    CreativeDirectorRequest,
    CreativePackageResponse,
    InterleavedBlock,
)
from services.gemini import interleaved as gemini_interleaved

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/creative-director", tags=["creative-director"])


@router.post("/generate", response_model=CreativePackageResponse)
async def generate_creative_package(req: CreativeDirectorRequest):
    """Generate a rich mixed-media creative package using Gemini interleaved output.

    The Creative Director agent thinks and creates like a human creative director,
    seamlessly weaving together narrative text and generated images in a single,
    fluid output stream — all from one Gemini API call.

    Returns an ordered list of `InterleavedBlock` objects:
    - `{"type": "text",  "content": "narrative text..."}`
    - `{"type": "image", "content": "<base64>", "mime_type": "image/png"}`

    Pass `include_narration: true` to also receive a base64-encoded WAV narration
    of all text blocks generated by Gemini TTS.
    """
    try:
        raw_blocks, narration_b64 = await gemini_interleaved.generate_creative_package(
            brief=req.brief,
            mode=req.mode.value,
            art_style=req.art_style,
            include_narration=req.include_narration,
            voice_id=req.voice_id,
        )
    except Exception as exc:
        logger.exception("Creative Director generation failed (mode=%s)", req.mode)
        raise HTTPException(status_code=500, detail=str(exc))

    blocks = [InterleavedBlock(**b) for b in raw_blocks]

    return CreativePackageResponse(
        package_id=uuid4(),
        mode=req.mode,
        brief=req.brief,
        blocks=blocks,
        total_images=sum(1 for b in blocks if b.type == "image"),
        total_text_blocks=sum(1 for b in blocks if b.type == "text"),
        narration_audio_b64=narration_b64,
    )


@router.post("/generate-stream")
async def stream_creative_package(req: CreativeDirectorRequest):
    """Stream a creative package as Server-Sent Events (SSE).

    Each SSE event is one JSON block delivered as it becomes available:
      data: {"type": "text",  "content": "..."}
      data: {"type": "image", "content": "<base64>", "mime_type": "image/png"}

    Final event:
      data: {"type": "done", "package_id": "...", "total_images": N, "total_text_blocks": M}

    On error:
      data: {"type": "error", "content": "error message"}

    Note: blocks are streamed one-by-one after the Gemini call completes — this
    creates a progressive reveal effect without requiring a streaming Gemini API.
    """
    async def event_generator():
        try:
            raw_blocks, narration_b64 = await gemini_interleaved.generate_creative_package(
                brief=req.brief,
                mode=req.mode.value,
                art_style=req.art_style,
                include_narration=req.include_narration,
                voice_id=req.voice_id,
            )
            for block in raw_blocks:
                yield f"data: {json.dumps(block)}\n\n"

            summary: dict = {
                "type": "done",
                "package_id": str(uuid4()),
                "total_images": sum(1 for b in raw_blocks if b["type"] == "image"),
                "total_text_blocks": sum(1 for b in raw_blocks if b["type"] == "text"),
            }
            if narration_b64:
                summary["narration_audio_b64"] = narration_b64
            yield f"data: {json.dumps(summary)}\n\n"

        except Exception as exc:
            logger.exception("SSE creative generation failed (mode=%s)", req.mode)
            yield f"data: {json.dumps({'type': 'error', 'content': str(exc)})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )
