import logging
from datetime import datetime, timezone
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException

from deps.auth import get_current_user
from models.schemas import (
    PlatformPostResult,
    PublishRequest,
    PublishResponse,
)
from services.integrations import social_publish
from services.storage import firestore_db

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1", tags=["publish"])


@router.post("/projects/{project_id}/publish", response_model=PublishResponse)
async def publish_project(project_id: UUID, request: PublishRequest, current_user: dict = Depends(get_current_user)):
    """Publish generated videos to social media platforms.

    Uses official platform APIs: YouTube Data API v3, Meta Graph API (Instagram),
    TikTok Content Posting API v2. Runs all platforms concurrently — partial
    success is reported if one platform fails.

    Requires that the pipeline has already been run for this project
    (videos must exist in S3 at projects/{id}/{platform}/final.mp4).
    """
    # Verify ownership before publishing (also fetch doc for social_copy derivation)
    project_doc = await firestore_db.get_project_for_user(str(project_id), current_user["uid"])

    # Build social_copy dict from request or auto-derive from project data
    social_copy: dict[str, dict] = {}
    if request.social_copy:
        for key, copy in request.social_copy.items():
            social_copy[key] = copy.model_dump()
    else:
        # Auto-derive title/caption/hashtags from project hook + script
        doc: dict = project_doc  # always a dict (get_project_for_user raises on miss)
        script = doc.get("script") or {}
        script_social_copy = script.get("social_copy") or {}
        hook = doc.get("hook") or ""
        voiceover = doc.get("voiceover_full_script") or ""

        # Prefer existing per-platform copy from the script (generated by the AI agent)
        existing: dict = (
            script_social_copy.get("youtube_shorts")
            or script_social_copy.get("instagram_reels")
            or script_social_copy.get("youtube")
            or (next(iter(script_social_copy.values())) if script_social_copy else {})
        )

        derived_title = existing.get("title") or hook[:97] or "New Video"
        derived_caption = existing.get("caption") or voiceover[:500] or hook
        derived_hashtags = existing.get("hashtags") or []

        _base_copy = {
            "title": derived_title,
            "caption": derived_caption,
            "hashtags": derived_hashtags,
        }
        social_copy = {
            "youtube": _base_copy,
            "youtube_shorts": _base_copy,
            "instagram": _base_copy,
            "instagram_reels": _base_copy,
            "tiktok": _base_copy,
        }

    platform_names = [p.value for p in request.platforms]

    results = await social_publish.publish_to_platforms(
        project_id=str(project_id),
        uid=current_user["uid"],
        platforms=platform_names,
        social_copy=social_copy,
        schedule=request.schedule,
        export_id=request.export_id,
    )

    posts = [
        PlatformPostResult(
            platform=r["platform"],
            status=r["status"],
            post_url=r.get("post_url"),
            screenshot_url=r.get("screenshot_url"),
            error=r.get("error"),
        )
        for r in results
    ]

    # Determine overall status
    statuses = {p.status for p in posts}
    if all(s in ("published", "scheduled") for s in statuses):
        overall = "completed"
    elif any(s in ("published", "scheduled") for s in statuses):
        overall = "partial"
    else:
        overall = "failed"

    return PublishResponse(
        project_id=project_id,
        status=overall,
        posts=posts,
        completed_at=datetime.now(timezone.utc),
    )
