steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - timeline-render-worker/Dockerfile
      - -t
      - $_IMAGE
      - ./timeline-render-worker

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_IMAGE

substitutions:
  _IMAGE: us-central1-docker.pkg.dev/voicevid/voicevid/render:latest

images:
  - $_IMAGE

options:
  logging: CLOUD_LOGGING_ONLY
